VERSION: 2
PREFIX: 2-node-env2
CEOS_IMAGE: ceos:4.29.0.2F
PUBLISH_BASE:
  22/tcp: 20022
  23/tcp: 20123
  443/tcp: 20443
driver: bridge
links:
  - endpoints: [ceos1:eth1, ceos2:eth2]
  - endpoints: [ceos1:eth2, ceos2:eth1]
