---
ansible_host: localhost
ansible_connection: httpapi
ansible_network_os: eos
ansible_user: admin
ansible_password: arista
ansible_become: yes
ansible_become_method: enable

provider:
  transport: eapi  
